import type { Character } from "./types";

/**
 * ROSTER DATA
 * ------------------------------------------------------------------
 * This is the only file you need to touch to add, reorder, or edit
 * characters. See README.md -> "Adding a new character" for the
 * full walkthrough.
 *
 * `thumbnail` / `mainArtwork` / gallery paths point into /public.
 * The placeholder files referenced below were generated by
 * scripts/generate-placeholder-art.mjs -- replace them with real
 * artwork whenever it's ready and nothing else needs to change.
 * ------------------------------------------------------------------
 */
export const characters: Character[] = [
  {
    id: "c1",
    slug: "kestrel-vane",
    name: "Kestrel Vane",
    title: "The Last Cartographer",
    description:
      "A wayfinder who maps places that stop existing once she leaves them. Wool, brass, and weathered leather; always mid-departure.",
    lore:
      "Kestrel was born in a border town that no longer appears on any map -- including the ones she draws herself. She's spent a decade trying to prove it existed. Her coat carries the dust of a dozen countries and the pins of places only she remembers.",
    designNotes:
      "The silhouette leans utilitarian: layered outerwear, a low center of gravity, and asymmetry in the strap placement to suggest constant movement. Palette pulled from aged paper and oxidized brass rather than pure fantasy tones -- the goal was 'explorer,' not 'wizard.'",
    displayMode: "full-body",
    thumbnail: "/characters/kestrel-vane/thumbnail.svg",
    mainArtwork: "/characters/kestrel-vane/main.svg",
    theme: {
      backgroundColor: "#2b1710",
      accentColor: "#e0a458",
      secondaryColor: "#5c2f1a",
      textColor: "#f6ede0",
    },
    gallery: {
      finalArtwork: [
        "/characters/kestrel-vane/final-1.svg",
        "/characters/kestrel-vane/final-2.svg",
      ],
      alternateOutfits: ["/characters/kestrel-vane/outfit-1.svg"],
      conceptArt: [
        "/characters/kestrel-vane/concept-1.svg",
        "/characters/kestrel-vane/concept-2.svg",
      ],
    },
  },
  {
    id: "c2",
    slug: "ondine-marchetti",
    name: "Ondine Marchetti",
    title: "Low Tide",
    description:
      "A free-diver-turned-courier who moves cargo between coastal cities no one admits are still flooding. Wetsuit tech reworked as streetwear.",
    lore:
      "Ondine grew up on a pier that's now three meters underwater. She never left -- she just learned to work below the new waterline, ferrying packages between the drowned districts other couriers won't enter.",
    designNotes:
      "Modern silhouette built from real dive-gear references: seam taping, neoprene panel lines, and a harness system that reads as function first, fashion second. Cool palette with a single warm accent to keep the eye anchored.",
    displayMode: "full-body",
    thumbnail: "/characters/ondine-marchetti/thumbnail.svg",
    mainArtwork: "/characters/ondine-marchetti/main.svg",
    theme: {
      backgroundColor: "#0c2733",
      accentColor: "#5fd0d6",
      secondaryColor: "#134a54",
      textColor: "#eaf7f8",
    },
    gallery: {
      finalArtwork: [
        "/characters/ondine-marchetti/final-1.svg",
        "/characters/ondine-marchetti/final-2.svg",
        "/characters/ondine-marchetti/final-3.svg",
      ],
      turnarounds: [
        "/characters/ondine-marchetti/turn-1.svg",
        "/characters/ondine-marchetti/turn-2.svg",
        "/characters/ondine-marchetti/turn-3.svg",
      ],
      expressions: [
        "/characters/ondine-marchetti/expr-1.svg",
        "/characters/ondine-marchetti/expr-2.svg",
      ],
    },
  },
  {
    id: "c3",
    slug: "sable-ferro",
    name: "Sable Ferro",
    title: "Iron Vespers",
    description:
      "A disgraced court armorer who forges her own ceremonial plate each year and wears it once, then melts it down. Headshot study -- full figure in progress.",
    lore:
      "Every year on the same night, Sable dons a suit of armor no one else has ever seen, walks the old palace wall alone, and has it destroyed by morning. No one knows why. She has never explained it, even to the one person who's asked twice.",
    designNotes:
      "This one's still a bust study -- the full-body pass hasn't been painted yet, so the portrait carries the presentation alone: heavy value contrast on the visor, a single warm rim light, and engraved surface detail kept dense only around the face.",
    displayMode: "bust",
    thumbnail: "/characters/sable-ferro/thumbnail.svg",
    mainArtwork: "/characters/sable-ferro/main.svg",
    theme: {
      backgroundColor: "#231029",
      accentColor: "#c48fe0",
      secondaryColor: "#40174d",
      textColor: "#f4e9f7",
    },
    gallery: {
      finalArtwork: ["/characters/sable-ferro/final-1.svg"],
      detailStudies: [
        "/characters/sable-ferro/detail-1.svg",
        "/characters/sable-ferro/detail-2.svg",
      ],
    },
  },
  {
    id: "c4",
    slug: "juno-halcyon",
    name: "Juno Halcyon",
    title: "Static Bloom",
    description:
      "A botanist who replaced most of her left arm with a growth-accelerator rig after a lab accident. Half greenhouse, half circuit board.",
    lore:
      "Juno's research into rapid tissue regeneration went sideways during a containment breach. Rather than amputate what the accident changed, she built around it -- now her prosthetic doubles as a portable propagation lab for the plant strains only she can grow.",
    designNotes:
      "Deliberately asymmetric design: organic curves on one side, hard mechanical linework on the other, meeting at the collarbone. Palette split the same way -- acid lime for the tech, warm magenta for the biological.",
    displayMode: "full-body",
    thumbnail: "/characters/juno-halcyon/thumbnail.svg",
    mainArtwork: "/characters/juno-halcyon/main.svg",
    theme: {
      backgroundColor: "#180a24",
      accentColor: "#d4f24c",
      secondaryColor: "#5c1a6b",
      textColor: "#f3edf9",
    },
    gallery: {
      finalArtwork: [
        "/characters/juno-halcyon/final-1.svg",
        "/characters/juno-halcyon/final-2.svg",
      ],
      alternateOutfits: ["/characters/juno-halcyon/outfit-1.svg"],
      turnarounds: [
        "/characters/juno-halcyon/turn-1.svg",
        "/characters/juno-halcyon/turn-2.svg",
        "/characters/juno-halcyon/turn-3.svg",
      ],
      conceptArt: ["/characters/juno-halcyon/concept-1.svg"],
    },
  },
  {
    id: "c5",
    slug: "percival-doyle",
    name: "Percival Doyle",
    title: "The Understudy",
    description:
      "A stage actor who has played the same supporting role eleven seasons running and has quietly started rewriting his lines. Headshot only, styled like a cast photo.",
    lore:
      "Percival auditions for the lead every year. Every year he's cast as the same minor character. This season, without telling the director, he's been adding half a line to every performance -- testing how long it takes anyone to notice.",
    designNotes:
      "Composed deliberately like a theatrical cast portrait rather than a game portrait -- three-quarter lighting, a plain backdrop, and a costume collar that implies a full outfit without needing the rest of the figure drawn.",
    displayMode: "portrait",
    thumbnail: "/characters/percival-doyle/thumbnail.svg",
    mainArtwork: "/characters/percival-doyle/main.svg",
    theme: {
      backgroundColor: "#14200f",
      accentColor: "#c9a24b",
      secondaryColor: "#26401b",
      textColor: "#f1efe4",
    },
    gallery: {
      finalArtwork: ["/characters/percival-doyle/final-1.svg"],
      expressions: [
        "/characters/percival-doyle/expr-1.svg",
        "/characters/percival-doyle/expr-2.svg",
        "/characters/percival-doyle/expr-3.svg",
      ],
    },
  },
  {
    id: "c6",
    slug: "rhea-solheim",
    name: "Rhea Solheim",
    title: "Winter's Ledger",
    description:
      "A village accountant who moonlights keeping accounts for something that isn't a village anymore. Fur, wax seals, and a ledger that writes back.",
    lore:
      "Rhea took over the town's books after her mother disappeared into the tree line one winter. The numbers have never quite added up since -- and lately, some of the entries in the ledger appear in a handwriting that isn't hers.",
    designNotes:
      "Historical Nordic reference base pushed slightly wrong: perfectly symmetrical embroidery, a ledger clasp that doesn't match any known metal. Cold, desaturated palette with one warm accent -- the wax seal red -- kept small and deliberate.",
    displayMode: "full-body",
    thumbnail: "/characters/rhea-solheim/thumbnail.svg",
    mainArtwork: "/characters/rhea-solheim/main.svg",
    theme: {
      backgroundColor: "#101820",
      accentColor: "#bcd6e0",
      secondaryColor: "#25404d",
      textColor: "#eef6f8",
    },
    gallery: {
      finalArtwork: [
        "/characters/rhea-solheim/final-1.svg",
        "/characters/rhea-solheim/final-2.svg",
      ],
      alternateOutfits: [
        "/characters/rhea-solheim/outfit-1.svg",
        "/characters/rhea-solheim/outfit-2.svg",
      ],
      detailStudies: ["/characters/rhea-solheim/detail-1.svg"],
    },
  },
];

export function getCharacter(slug: string): Character | undefined {
  return characters.find((c) => c.slug === slug);
}

export function getCharacterIndex(slug: string): number {
  return characters.findIndex((c) => c.slug === slug);
}
